### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by gnovelli** [tedwang-tw/docker-aosp-v5#1]
I have pulled your container following your instructions:
docker pull tedwang/aosp-v5:latest
docker run ...

Then I get aosp shell:
0 android@ ~ $ cd aosp
0 android@ ~/aosp $ git config --global user.email "name@example.com"
0 android@ ~/aosp $ git config --global user.name "My Name"
0 android@ ~/aosp $ repo init -u https://android.googlesource.com/platform/manifest
0 android@ ~/aosp $ repo sync
0 android@ ~/aosp $ source build/envsetup.sh
0 android@ ~/aosp $ lunch ......

Trying lunch for some targets, including default I get two errors:
1) unzip missing (I have updated the container to get such package in the container)
2) Build error. The following is the tail of the output:
JarJar: out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/classes-jarjar.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.tonicsystems.jarjar.MainUtil.runMain(MainUtil.java:37)
    at com.tonicsystems.jarjar.Main.main(Main.java:50)
Caused by: java.lang.NoClassDefFoundError: org/objectweb/asm/commons/Remapper
    at com.tonicsystems.jarjar.Main.process(Main.java:93)
    ... 6 more
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.commons.Remapper
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 7 more
make: **\* [out/target/common/obj/JAVA_LIBRARIES/conscrypt_intermediates/classes-jarjar.jar] Error 1

Regards.

**Comment by tedwang-tw** [comment]
Hi gnovelli,

Since this docker image is for AOSP Lollipop version,
have you tried it with the **Lollipop** source branch?
When I created this docker image, I used it with below repo:

```
repo init -u https://android.googlesource.com/platform/manifest -b android-l-preview_r2
```

Regards,

**Comment by tedwang-tw** [comment]
I'll add a note in the readme for this comment.

**Comment by tedwang-tw** [comment]
Build finished.
